export const pokemons = [
  {
    id: 1,
    name: "Bulbasaur",
    height: "7",
    weight: "69",
    types: ["grass", "poison"],
    base_experience: "64",
    abilities: ["overgrow", "chlorophyll"],
    hp: "45",
    attack: "49",
    defense: "49",
    special_attack: "65",
    special_defense: "65",
    speed: "45",
  },
  {
    id: 2,
    name: "Ivysaur",
    height: "10",
    weight: "130",
    types: ["grass", "poison"],
    base_experience: "142",
    abilities: ["overgrow", "chlorophyll"],
    hp: "60",
    attack: "62",
    defense: "63",
    special_attack: "80",
    special_defense: "80",
    speed: "60",
  },
  {
    id: 3,
    name: "Venusaur",
    height: "20",
    weight: "1000",
    types: ["grass", "poison"],
    base_experience: "236",
    abilities: ["overgrow", "chlorophyll"],
    hp: "80",
    attack: "82",
    defense: "83",
    special_attack: "100",
    special_defense: "100",
    speed: "80",
  },
  {
    id: 4,
    name: "Charmander",
    height: "6",
    weight: "85",
    types: ["fire"],
    base_experience: "62",
    abilities: ["blaze", "solar-power"],
    hp: "39",
    attack: "52",
    defense: "43",
    special_attack: "60",
    special_defense: "50",
    speed: "65",
  },
  {
    id: 5,
    name: "Charmeleon",
    height: "11",
    weight: "190",
    types: ["fire"],
    base_experience: "142",
    abilities: ["blaze", "solar-power"],
    hp: "58",
    attack: "64",
    defense: "58",
    special_attack: "80",
    special_defense: "65",
    speed: "80",
  },
  {
    id: 6,
    name: "Charizard",
    height: "17",
    weight: "905",
    types: ["fire", "flying"],
    base_experience: "240",
    abilities: ["blaze", "solar-power"],
    hp: "78",
    attack: "84",
    defense: "78",
    special_attack: "109",
    special_defense: "85",
    speed: "100",
  },
  {
    id: 7,
    name: "Squirtle",
    height: "5",
    weight: "90",
    types: ["water"],
    base_experience: "63",
    abilities: ["torrent", "rain-dish"],
    hp: "44",
    attack: "48",
    defense: "65",
    special_attack: "50",
    special_defense: "64",
    speed: "43",
  },
  {
    id: 8,
    name: "Wartortle",
    height: "10",
    weight: "225",
    types: ["water"],
    base_experience: "142",
    abilities: ["torrent", "rain-dish"],
    hp: "59",
    attack: "63",
    defense: "80",
    special_attack: "65",
    special_defense: "80",
    speed: "58",
  },
  {
    id: 9,
    name: "Blastoise",
    height: "16",
    weight: "855",
    types: ["water"],
    base_experience: "239",
    abilities: ["torrent", "rain-dish"],
    hp: "79",
    attack: "83",
    defense: "100",
    special_attack: "85",
    special_defense: "105",
    speed: "78",
  },
  {
    id: 10,
    name: "Caterpie",
    height: "3",
    weight: "29",
    types: ["bug"],
    base_experience: "39",
    abilities: ["shield-dust", "run-away"],
    hp: "45",
    attack: "30",
    defense: "35",
    special_attack: "20",
    special_defense: "20",
    speed: "45",
  },
];
